### PR TITLE
Parse code blocks in rich text fields as markdown

### PR DESCRIPTION
**Pull request by briaguya**

### CODE REVIEW

**Comment by easherma** [comment]
@briaguya can you rename this PR being a little more specific about what its for?

**Comment by briaguya** [comment]
@easherma when I made the branch name I was trying a lot of different things, naming conventions had gone out the window by then and I just wanted to see something work in a PR app

**Comment by easherma** [comment]
@briaguya s'yall good I just forget what its for everytime i peruse our open branches :-D

**Comment by briaguya** [comment]
@easherma I figured we'd be doing a bit of toe-stepping between this and https://github.com/cityofaustin/techstack/issues/2479 so I went ahead and copied some of the code you had in #457 and pulled it in here

**Pull request merged**
